### PR TITLE
inskrivning utlandskagare skyddadid

### PR DESCRIPTION
**Pull request by mulfvik**
This PR solves issue #1  and #2 .

### CODE REVIEW

**Comment by afogelberg** [comment]
Thanks the contribution @mulfvik . Getting more information from inskrivning direkt is indeed useful. I think that at this point we need to deal with a couple of questions. As default I think we need to hide the id number and skyddad identitet. Another question is how much information we should include in the default report. I suggest we make the report more flexible to include the information needed for various implementations.

**Comment by mulfvik** [comment]
Yes, I agree.  There should be some config for different usecases. 
About skyddad identitet, do you mean to redirect the report to something like "Not available" if agare has skyddad identitet or just dont render the string "Skyddad identitet"? I think in last example there could be confusion for the user to only see parts of the information. (Or mayby just replace the string with something more general)
I agree that id-numbers should be hidden by default.

**Comment by afogelberg** [comment]
@mulfvik I'm working on a PR that will make the report configurable where the id-number will be hidden by default. I'm still not sure though how to handle 'skyddad identitet'.

**Comment by mulfvik** [comment]
@afogelberg Ok, sounds good

**Pull request closed without merging**
